apiVersion: v1
kind: Service
metadata:
  labels:
    app: flaskapp-depl
  name: flaskapp-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: flaskapp-depl
  type: ClusterIP
